approve_by_comment: true
approve_regex: '^(LGTM|:shipit:|:+1:)'
reject_regex: '^:-1:'
reset_on_push: true
author_approval: ignored
reviewers:
    required: 1
    members:
        - ChristianMurphy
        - poojaRal
